//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace treinamento.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class programa_GODEVEntities : DbContext
    {
        public programa_GODEVEntities()
            : base("name=programa_GODEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cafe> cafe { get; set; }
        public virtual DbSet<pessoa> pessoa { get; set; }
        public virtual DbSet<sala> sala { get; set; }
    }
}
